/* Main.ino file generated by New Project wizard
 *
 * Created:   Thu Nov 17 2016
 * Processor: Arduino Uno
 * Compiler:  Arduino AVR (Proteus)
 */
#include<LiquidCrystal.h>
#include<stdlib.h>

LiquidCrystal lcd(9, 8, 5, 4, 3, 2);

//#define YES DETECTED
//#define NO NOT_DETECTED

const char *node2_sensor_name[] = {"Node Id",
                "sensor 1 : LM 35",
                "sensor 2 : MQ-9 GAS",
                "sensor 3 : BMP085",
                "sensor 4 : IR",
                "sensor 5 : Flex"};
const char *node2_data[] = {"Node ID = ",
                "Temperature(C) = ",
                "RS/R0 (ppm)= ",
                "Pressure (pa) = ",
                "Object = ",
                "Flex Mov. = "};

void node2_recieved_data(float arr0[])
{
    int i;
    for(i = 0;i<6;i++)
    {
      delay(1000);
      lcd.clear();
      lcd.setCursor(0,0);
      lcd.print(*(node2_sensor_name+i));
      lcd.setCursor(0,1);
        lcd.print(*(node2_data+i));
        if(i == 4){
            if(arr0[i])
                lcd.print("DETECTED");
            else
                lcd.print("NOT_DETECTED");
        }
        else
            lcd.print(arr0[i]);
    }
}


void init_lcd()
{
    lcd.begin(20,4);
    lcd.clear();
    lcd.setCursor(0,0);
    lcd.print("   SIGMA TRAINERS  ");
    lcd.setCursor(0,1);
    lcd.print("         &         ");
    lcd.setCursor(0,2);
    lcd.print("        KITS       ");
    lcd.setCursor(0,3);
    lcd.print("       WSN100L     ");
    delay(200);
    lcd.clear();
}


int read_sensor_pir(void){
    int status = digitalRead(A4);
    return status; // if 0 not detected and if 1 detected
};

float read_sensor_gas(void){
   int x = 800;
     float sensor_volt=(float)x/*analogRead(A1)*//1024*5.0;
    float RS_gas = (5.0-sensor_volt)/sensor_volt; // omit *RL
    float ratio = RS_gas/1.66;//R0;  // ratio = RS/R0 
    return ratio; 
};

float read_sensor_lm35(void){
    float temp = (analogRead(0))*(5000/1024);
    return temp /8.31; 
};

void setup()
 { // put your setup code here, to run once:
 Serial.begin(9600);
 init_lcd();			//lcd init
 pinMode(A4,INPUT);		// pir init
 }

 
void loop()
 { // put your main code here, to run repeatedly:
 float arr0[6] = {2,0,0,0,0,0};
 arr0[1] = read_sensor_lm35();
 arr0[2] = read_sensor_gas();
 arr0[4] = read_sensor_pir();
  node2_recieved_data(arr0);

 }

